[workspace]
members = [
    "brucket-ast",
    "brucket-analyzer",
    "brucket-cli",
    "brucket-interpreter",
    "brucket-parser",
    "brucket-quote",
    "brucket-transpiler",
    "c-generator"
]
