[package]
name = "brucket-transpiler"
version = "0.1.0"
authors = ["Piotr Dobiech"]
edition = "2018"

[dependencies]
brucket-ast = { path = "../brucket-ast" }
brucket-analyzer = { path = "../brucket-analyzer" }
c-generator = { path = "../c-generator" }
