[package]
name = "brucket-ast"
version = "0.1.0"
authors = ["Piotr Dobiech"]
edition = "2018"

[dependencies]
maplit = "1.0.2"

[dependencies.derive_more]
version = "0.99.16"
default-features = false
features = ["constructor", "is_variant", "display"]
